name: Docker Image CI

on:
  push:
    branches: [ "main","testing","release" ]
jobs:
  push:
    # needs: build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Push the Docker image
      uses: actions/checkout@v4
    
    - name: Setup env
      run: echo "TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/safewoo/safewoo-v2ray-mono:${{ env.TAG_NAME }}